### ISSUE TITLE
How to evaluate on a different class name ?

### ISSUE THREAD

**Issue by shashankvasisht** [cguindel/eval_kitti#17]
Hi, I trained a model by combining all the different vehicle classes like Car, Truck, Bus, Tram etc as one single class called "Vehicle". How should i modify the script to make it work for this combined class.

I tried changing 
void initGlobals () {
  CLASS_NAMES.push_back("car");
  CLASS_NAMES.push_back("pedestrian");
  CLASS_NAMES.push_back("cyclist");
  CLASS_NAMES.push_back("van");
  CLASS_NAMES.push_back("truck");
  CLASS_NAMES.push_back("person_sitting");
  CLASS_NAMES.push_back("tram");
}

to 

void initGlobals () {
  CLASS_NAMES.push_back("vehicle");
  CLASS_NAMES.push_back("pedestrian");
  CLASS_NAMES.push_back("cyclist");
}

However i am still getting the following error:

evaluate_object smoke_common test_2
Starting evaluation...
Results list: ../lists/test_2.txt
mkdir: cannot create directory ‘results/smoke_common/plot’: File exists
Getting valid images...
File loaded
Loading detections...
-----------
GT STATS
-----------
vehicle : 37125
pedestrian : 9633
cyclist : 902
-----------
DET STATS
-----------
vehicle : 27409
pedestrian : 6632
cyclist : 558
  done.
vehicle: Starting 2D evaluation (Easy/Moderate/Hard)...
Getting detection scores to compute thresholds
Evaluating on 27017 valid ground-truth instances and 18498 valid detections
Computing statistics
evaluate_object: /media/ADAS1/Shashank/sample_data_for_smoke/kitti/evaluation_toolkit/evaluate_object.cpp:637: tPrData computeStatistics(CLASSES, const std::vector<tGroundtruth>&, const std::vector<tDetection>&, const std::vector<tGroundtruth>&, const std::vector<int>&, const std::vector<int>&, bool, double (*)(tDetection, tGroundtruth, int32_t), METRIC, bool, double, double): Assertion `gt_bin<VIEWP_BINS && gt_bin>=0' failed.
Aborted (core dumped)

**Comment by shashankvasisht** [comment]
Resolved

**Comment by SofianeB-03** [comment]
Hello shashankvasisht, how did you solve it please?

**Comment by cguindel** [comment]
Perhaps @shashankvasisht can shed more light on the matter, but I think that the assertion error he was getting was related to the alpha angle of the detections, and therefore has nothing to do with the name of the classes (the change he reports seems to be OK). Are you facing a similar issue, @SofianeB-03?

**Comment by shashankvasisht** [comment]
@cguindel Yes it was an error related to AOS, the angle in my custom GT was out of the prescribed kitti range. As soon as i realized i closed the issue. The change for different class name is correct.

**Comment by cguindel** [comment]
Ok, thank you!
