### ISSUE TITLE
stats_car_detection.txt not found

### ISSUE THREAD

**Issue by qfwysw** [cguindel/eval_kitti#18]
Thank you for the good source code. I use the code to evaluate the 3d box. Then I used the code "./parser.py exp1" to get AP.  The code produce the text file named "stats_car_detection_3d" but the code need the text file named "stats_car_detection". Then should I modify the "detection" to the "detection_3d" in parser.py?

**Comment by cguindel** [comment]
Hi @qfwysw. You can just use `./parser.py exp1 3d` and it should give you the 3D results. Similarly, for the BEV evaluation the command would be: `./parser.py exp1 ground`

**Comment by qfwysw** [comment]
> Hi @qfwysw. You can just use `./parser.py exp1 3d` and it should give you the 3D results. Similarly, for the BEV evaluation the command would be: `./parser.py exp1 ground`

Thanks for your quick reply. It solves my problem.
