### ISSUE TITLE
How to use the evaluate_object to upload results?

### ISSUE THREAD

**Issue by 408550969** [cguindel/eval_kitti#6]
Hi,I want to upload my results to Kitti. How do I use evaluate_object.cpp under caffe?How to test speed?

**Comment by cguindel** [comment]
Hi @408550969, 
1. If you only want to upload your results to KITTI, you do not need the code in this repository. Just follow the instructions in the [official KITTI site](http://www.cvlibs.net/datasets/kitti/user_submit.php). This fork is useful if you want to evaluate your results using a custom validation set before uploading the final results to the public benchmark.
2. The evaluation is independent of the algorithm/framework that you are trying to evaluate. Just generate result files according to the KITTI format.
3. As I said in the previous point, this evaluation script is not aware of the detection method itself, so you need to measure detection time beforehand.

I recommend you to get familiar with the KITTI object dataset before trying the evaluation scripts.

**Comment by cguindel** [comment]
Closed due to inactivity
