### ISSUE TITLE
No result

### ISSUE THREAD

**Issue by langelesl** [cguindel/eval_kitti#7]
Hi,

thank you very much for sharing the codes. Here I have 2 questions:

1. To figure out how the evaluation function works, I made the folders following your instruction in README.md, and I copied 5 ground truth files (000000~000004.txt) from label_2 folder of KITTI object Benchmark into the results/data folder as results, and I add a fake confidence (like 0.99) for every detected object at the end of every line in .txt. (the paths of the corresponding images are added in validation.txt). However, after I ran the command "./evaluate_object data validation", an empty folder named plot was built in results/data/ without any contents. And the output in terminal is like this:

![Screenshot from 2019-03-09 22-04-06](https://user-images.githubusercontent.com/45672268/54077364-7f145c80-42b7-11e9-8c05-26766591fe2d.png)

So I would like to ask you some advices about how I should run your evaluation code correctly, and  what the evaluated results should look like.

2. I have trained a model to do the 2d object detection on kitti dataset. Is that also possible for your evaluation code to evaluate the results of 2d object detection? If positive, what should I notice in making results.txt?

Thanks again.

**Comment by cguindel** [comment]
Hi, @langelesl,

1. I have tried to reproduce the error, and I have concluded that it might be related to the "list" file. The idea of the list file is enabling the use of train/validation splits with non-consecutive indices. The file must contain only the indices of the validation frames. In your case, what is the content of the file **lists/val.txt**? It should be something like this: 
```
0
1
2
3
4
```

2. Of course, the script can be used with 2D detections. You can either ignore the BEV/3D results or create result files where the unknown fields are assigned "undefined" values. So if you only have the bounding box coordinates (left, top, right, bottom pixel coordinates), an example line would be:
```
Car -1 -1 -10 503.89 169.71 590.61 190.13 -1 -1 -1 -1000 -1000 -1000 -10 0.99
```

Please let me know if fixing the list file solves your problem.

**Comment by cguindel** [comment]
Closed due to inactivity.
